package view;

import dao.AdministradorDAO;
import model.Administrador;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import util.SenhaUtil;
import util.ValidadorUtil;
import util.MascaraUtil;

public class TelaAdministrador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdministrador.class.getName());
    private AdministradorDAO administradorDAO
            = new AdministradorDAO();

    private int id_admin_selecionado = 0;

    public TelaAdministrador() {
        initComponents();

        MascaraUtil.aplicarMascaraTelefone(
                txtTelefone
        );

        setLocationRelativeTo(null);

        carregarTabela();
    }

    private void carregarTabela() {

        DefaultTableModel modelo
                = (DefaultTableModel) tableAdministradores.getModel();

        modelo.setRowCount(0);

        List<Administrador> lista
                = administradorDAO.listar();

        for (Administrador administrador
                : lista) {

            modelo.addRow(new Object[]{
                administrador.getId_adm(),
                administrador.getNome(),
                administrador.getEmail(),
                MascaraUtil.formatarTelefone(
                administrador.getTelefone()
                ),
                administrador.isStatus()
                ? "ATIVO"
                : "INATIVO"
            });
        }
    }

    private void limparCampos() {

        txtNome.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        txtTelefone.setText("");

        cbStatus.setSelectedItem("ATIVO");

        id_admin_selecionado = 0;

        tableAdministradores.clearSelection();

        txtNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        cbStatus = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdministradores = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 245));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo.setText("GERENCIAR ADMINISTRADORES");

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(38, 50, 56));
        lblNome.setText("Nome:");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(38, 50, 56));
        lblEmail.setText("Email:");

        lblSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(38, 50, 56));
        lblSenha.setText("Senha:");

        lblTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(38, 50, 56));
        lblTelefone.setText("Telefone:");

        lblStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(38, 50, 56));
        lblStatus.setText("Status:");

        txtTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(38, 50, 56));
        txtTelefone.setToolTipText("Telefone");
        txtTelefone.addActionListener(this::txtTelefoneActionPerformed);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(38, 50, 56));
        txtEmail.setToolTipText("Email");
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        txtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(38, 50, 56));
        txtSenha.setToolTipText("Senha");

        cbStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbStatus.setForeground(new java.awt.Color(38, 50, 56));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));
        cbStatus.setToolTipText("Status");
        cbStatus.addActionListener(this::cbStatusActionPerformed);

        btnCadastrar.setBackground(new java.awt.Color(76, 175, 80));
        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Cadastrar");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.setOpaque(true);
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        btnAlterar.setBackground(new java.awt.Color(33, 150, 243));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setFocusPainted(false);
        btnAlterar.setOpaque(true);
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(229, 57, 53));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setFocusPainted(false);
        btnExcluir.setOpaque(true);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(96, 125, 139));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar");
        btnLimpar.setBorderPainted(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setFocusPainted(false);
        btnLimpar.setOpaque(true);
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        lblTitulo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo2.setText("ADMINISTRADORES");

        tableAdministradores.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tableAdministradores.setForeground(new java.awt.Color(38, 50, 56));
        tableAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "E-mail", "Telefone", "Status"
            }
        ));
        tableAdministradores.setGridColor(new java.awt.Color(224, 224, 224));
        tableAdministradores.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tableAdministradores.setRowHeight(28);
        tableAdministradores.setSelectionBackground(new java.awt.Color(232, 245, 233));
        tableAdministradores.setSelectionForeground(new java.awt.Color(38, 50, 56));
        tableAdministradores.setShowGrid(true);
        tableAdministradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdministradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAdministradores);
        if (tableAdministradores.getColumnModel().getColumnCount() > 0) {
            tableAdministradores.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.setToolTipText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome)
                                .addComponent(txtEmail)
                                .addComponent(txtSenha)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtTelefone.getAccessibleContext().setAccessibleDescription("");
        txtEmail.getAccessibleContext().setAccessibleDescription("");
        txtSenha.getAccessibleContext().setAccessibleDescription("");
        cbStatus.getAccessibleContext().setAccessibleDescription("");
        txtNome.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (id_admin_selecionado == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um administrador."
            );

            return;
        }

        String nome
                = txtNome.getText().trim();

        String email
                = txtEmail.getText().trim();

        String senha
                = new String(
                        txtSenha.getPassword()
                );

        String telefone
                = MascaraUtil.somenteNumeros(
                        txtTelefone.getText()
                );

        if (nome.isEmpty()
                || email.isEmpty()
                || senha.isEmpty()
                || telefone.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return;
        }

        Administrador administrador
                = new Administrador();

        administrador.setId_adm(
                id_admin_selecionado
        );

        administrador.setNome(nome);
        administrador.setEmail(email);
        administrador.setSenha(senha);
        administrador.setTelefone(telefone);

        administrador.setStatus(
                "ATIVO".equals(
                        cbStatus
                                .getSelectedItem()
                                .toString()
                )
        );

        administradorDAO.atualizar(
                administrador
        );

        JOptionPane.showMessageDialog(
                this,
                "Administrador alterado com sucesso!"
        );

        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome
                = txtNome.getText().trim();

        String email
                = txtEmail.getText().trim();

        String senha
                = new String(
                        txtSenha.getPassword()
                );

        String telefone
                = MascaraUtil.somenteNumeros(
                        txtTelefone.getText()
                );

        if (nome.isEmpty()
                || email.isEmpty()
                || senha.isEmpty()
                || telefone.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return;
        }

        if (!ValidadorUtil.emailValido(email)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Informe um e-mail válido."
            );

            return;
        }

        if (telefone.length() < 10) {

            JOptionPane.showMessageDialog(
                    this,
                    "Informe um telefone válido."
            );

            return;
        }

        if (senha.length() < 6) {

            JOptionPane.showMessageDialog(
                    this,
                    "A senha deve possuir pelo menos 6 caracteres."
            );

            return;
        }

        Administrador administrador
                = new Administrador();

        administrador.setNome(nome);
        administrador.setEmail(email);
        administrador.setSenha(
                SenhaUtil.gerarHash(senha)
        );
        administrador.setTelefone(telefone);

        administrador.setStatus(
                "ATIVO".equals(
                        cbStatus
                                .getSelectedItem()
                                .toString()
                )
        );

        administradorDAO.cadastrar(
                administrador
        );

        JOptionPane.showMessageDialog(
                this,
                "Administrador cadastrado com sucesso!"
        );

        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tableAdministradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdministradoresMouseClicked
        int linha
                = tableAdministradores.getSelectedRow();

        if (linha < 0) {
            return;
        }

        id_admin_selecionado
                = Integer.parseInt(
                        tableAdministradores
                                .getValueAt(linha, 0)
                                .toString()
                );

        Administrador administrador
                = administradorDAO.buscarPorId(
                        id_admin_selecionado
                );

        if (administrador == null) {
            return;
        }

        txtNome.setText(
                administrador.getNome()
        );

        txtEmail.setText(
                administrador.getEmail()
        );

        txtSenha.setText("");

        txtTelefone.setText(
                MascaraUtil.formatarTelefone(
                        administrador.getTelefone()
                )
        );

        cbStatus.setSelectedItem(
                administrador.isStatus()
                ? "ATIVO"
                : "INATIVO"
        );
    }//GEN-LAST:event_tableAdministradoresMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (id_admin_selecionado == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um administrador."
            );

            return;
        }

        int resposta
                = JOptionPane.showConfirmDialog(
                        this,
                        "Deseja realmente excluir "
                        + "este administrador?",
                        "Confirmação",
                        JOptionPane.YES_NO_OPTION
                );

        if (resposta
                == JOptionPane.YES_OPTION) {

            administradorDAO.excluir(
                    id_admin_selecionado
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Administrador excluído com sucesso!"
            );

            limparCampos();
            carregarTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tableAdministradores;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
