package view;

import dao.RelatorioDAO;

import java.util.List;

import javax.swing.table.DefaultTableModel;

public class TelaRelatorios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorios.class.getName());

    private RelatorioDAO relatorioDAO
            = new RelatorioDAO();

    public TelaRelatorios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTipoRelatorio = new javax.swing.JLabel();
        cbTipoRelatorio = new javax.swing.JComboBox<>();
        btnGerar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitulo2 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRelatorio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 245));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo.setText("RELATÓRIOS");

        lblTipoRelatorio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTipoRelatorio.setForeground(new java.awt.Color(38, 50, 56));
        lblTipoRelatorio.setText("Tipo de Relatório:");

        cbTipoRelatorio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbTipoRelatorio.setForeground(new java.awt.Color(38, 50, 56));
        cbTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doações", "Solicitações", "Entregas", "Estoque" }));
        cbTipoRelatorio.setToolTipText("Tipo de Relatório");
        cbTipoRelatorio.addActionListener(this::cbTipoRelatorioActionPerformed);

        btnGerar.setBackground(new java.awt.Color(76, 175, 80));
        btnGerar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnGerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGerar.setText("Gerar");
        btnGerar.setToolTipText("Gerar");
        btnGerar.setBorderPainted(false);
        btnGerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerar.setFocusPainted(false);
        btnGerar.setOpaque(true);
        btnGerar.addActionListener(this::btnGerarActionPerformed);

        lblTitulo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo2.setText("RESULTADO");

        btnLimpar.setBackground(new java.awt.Color(96, 125, 139));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar");
        btnLimpar.setBorderPainted(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setFocusPainted(false);
        btnLimpar.setOpaque(true);
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        tableRelatorio.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tableRelatorio.setForeground(new java.awt.Color(38, 50, 56));
        tableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableRelatorio.setGridColor(new java.awt.Color(224, 224, 224));
        tableRelatorio.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tableRelatorio.setRowHeight(28);
        tableRelatorio.setSelectionBackground(new java.awt.Color(232, 245, 233));
        tableRelatorio.setSelectionForeground(new java.awt.Color(38, 50, 56));
        tableRelatorio.setShowGrid(true);
        jScrollPane1.setViewportView(tableRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTipoRelatorio)
                .addGap(18, 18, 18)
                .addComponent(cbTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerar)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblTitulo2)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoRelatorio)
                    .addComponent(cbTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerar))
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo2)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        String tipo
                = cbTipoRelatorio
                        .getSelectedItem()
                        .toString();

        DefaultTableModel modelo
                = (DefaultTableModel) tableRelatorio.getModel();

        modelo.setRowCount(0);

        List<Object[]> dados;

        if (tipo.equals("Doações")) {

            dados
                    = relatorioDAO.relatorioDoacoes();

            modelo.setColumnIdentifiers(
                    new Object[]{
                        "Doador",
                        "Alimento",
                        "Quantidade",
                        "Unidade",
                        "Validade"
                    }
            );

        } else if (tipo.equals("Solicitações")) {

            dados
                    = relatorioDAO.relatorioSolicitacoes();

            modelo.setColumnIdentifiers(
                    new Object[]{
                        "ID",
                        "Instituição",
                        "Data",
                        "Status"
                    }
            );

        } else if (tipo.equals("Entregas")) {

            dados
                    = relatorioDAO.relatorioEntregas();

            modelo.setColumnIdentifiers(
                    new Object[]{
                        "ID",
                        "Solicitação",
                        "Data",
                        "Responsável",
                        "Status"
                    }
            );

        } else {

            dados
                    = relatorioDAO.relatorioEstoque();

            modelo.setColumnIdentifiers(
                    new Object[]{
                        "Alimento",
                        "Categoria",
                        "Quantidade",
                        "Unidade",
                        "Validade",
                        "Status"
                    }
            );
        }

        for (Object[] linha : dados) {
            modelo.addRow(linha);
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        DefaultTableModel modelo
                = (DefaultTableModel) tableRelatorio.getModel();

        modelo.setRowCount(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cbTipoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRelatorios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbTipoRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTipoRelatorio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tableRelatorio;
    // End of variables declaration//GEN-END:variables
}
