package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import model.Administrador;
import javax.swing.JOptionPane;
import util.EstiloUtil;

public class TelaMenuAdministrador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuAdministrador.class.getName());
    private Administrador administrador;

    public TelaMenuAdministrador(Administrador administrador) {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon iconeOriginal = new ImageIcon(
                getClass().getResource(
                        "/imagens/pessoa.png"
                )
        );

        Image imagem = iconeOriginal.getImage()
                .getScaledInstance(
                        16,
                        16,
                        Image.SCALE_SMOOTH
                );

        lblIconeUsuario.setIcon(
                new ImageIcon(imagem)
        );
        
        EstiloUtil.definirLogo(
                lblLogo,
                "/imagens/logo_realimenta.png",
                180,
                180
        );

        this.administrador = administrador;

        lblIconeUsuario.setText(
                "Bem-vindo, "
                + administrador.getNome()
                + "!"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblIconeUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        itemCategorias = new javax.swing.JMenuItem();
        itemDoadores = new javax.swing.JMenuItem();
        itemInstituicoes = new javax.swing.JMenuItem();
        itemAlimentos = new javax.swing.JMenuItem();
        itemAdministradores = new javax.swing.JMenuItem();
        menuSolicitacoes = new javax.swing.JMenu();
        itemSolicitacoes = new javax.swing.JMenuItem();
        itemAprovacao = new javax.swing.JMenuItem();
        itemEntregas = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemRelatorios = new javax.swing.JMenuItem();
        itemGraficos = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 245));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(27, 94, 32));
        lblTitulo.setText("ReAlimenta - ADMINISTRADOR");

        lblSubtitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(96, 125, 139));
        lblSubtitulo.setText("Banco de Alimentos Solidário");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_realimenta.png"))); // NOI18N

        lblIconeUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIconeUsuario.setForeground(new java.awt.Color(38, 50, 56));
        lblIconeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa.png"))); // NOI18N

        menuCadastros.setText("Cadastros");

        itemCategorias.setText("Categorias");
        itemCategorias.addActionListener(this::itemCategoriasActionPerformed);
        menuCadastros.add(itemCategorias);

        itemDoadores.setText("Doadores");
        itemDoadores.addActionListener(this::itemDoadoresActionPerformed);
        menuCadastros.add(itemDoadores);

        itemInstituicoes.setText("Instituições");
        itemInstituicoes.addActionListener(this::itemInstituicoesActionPerformed);
        menuCadastros.add(itemInstituicoes);

        itemAlimentos.setText("Alimentos");
        itemAlimentos.addActionListener(this::itemAlimentosActionPerformed);
        menuCadastros.add(itemAlimentos);

        itemAdministradores.setText("Administradores");
        itemAdministradores.addActionListener(this::itemAdministradoresActionPerformed);
        menuCadastros.add(itemAdministradores);

        jMenuBar1.add(menuCadastros);

        menuSolicitacoes.setText("Operações");

        itemSolicitacoes.setText("Solicitações");
        itemSolicitacoes.addActionListener(this::itemSolicitacoesActionPerformed);
        menuSolicitacoes.add(itemSolicitacoes);

        itemAprovacao.setText("Analisar Solicitações");
        itemAprovacao.addActionListener(this::itemAprovacaoActionPerformed);
        menuSolicitacoes.add(itemAprovacao);

        itemEntregas.setText("Entregas");
        itemEntregas.addActionListener(this::itemEntregasActionPerformed);
        menuSolicitacoes.add(itemEntregas);

        jMenuBar1.add(menuSolicitacoes);

        menuRelatorios.setText("Relatórios");

        itemRelatorios.setText("Relatórios");
        itemRelatorios.addActionListener(this::itemRelatoriosActionPerformed);
        menuRelatorios.add(itemRelatorios);

        itemGraficos.setText("Gráficos");
        itemGraficos.addActionListener(this::itemGraficosActionPerformed);
        menuRelatorios.add(itemGraficos);

        jMenuBar1.add(menuRelatorios);

        menuSistema.setText("Sistemas");

        itemSair.setText("Sair");
        itemSair.addActionListener(this::itemSairActionPerformed);
        menuSistema.add(itemSair);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubtitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblIconeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addGap(50, 50, 50)
                .addComponent(lblIconeUsuario)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemInstituicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInstituicoesActionPerformed
        new TelaInstituicao().setVisible(true);
    }//GEN-LAST:event_itemInstituicoesActionPerformed

    private void itemSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSolicitacoesActionPerformed
        new TelaSolicitacao().setVisible(true);
    }//GEN-LAST:event_itemSolicitacoesActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja sair do sistema?",
                "Sair",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {

            new TelaLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriasActionPerformed
        new TelaCategoria().setVisible(true);
    }//GEN-LAST:event_itemCategoriasActionPerformed

    private void itemDoadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDoadoresActionPerformed
        new TelaDoador().setVisible(true);
    }//GEN-LAST:event_itemDoadoresActionPerformed

    private void itemAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlimentosActionPerformed
        new TelaAlimento().setVisible(true);
    }//GEN-LAST:event_itemAlimentosActionPerformed

    private void itemAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdministradoresActionPerformed
        new TelaAdministrador().setVisible(true);
    }//GEN-LAST:event_itemAdministradoresActionPerformed

    private void itemAprovacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAprovacaoActionPerformed
        new TelaAprovacaoSolicitacao().setVisible(true);
    }//GEN-LAST:event_itemAprovacaoActionPerformed

    private void itemEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntregasActionPerformed
        new TelaEntrega().setVisible(true);
    }//GEN-LAST:event_itemEntregasActionPerformed

    private void itemRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatoriosActionPerformed
        new TelaRelatorios().setVisible(true);
    }//GEN-LAST:event_itemRelatoriosActionPerformed

    private void itemGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGraficosActionPerformed
        new TelaGraficos().setVisible(true);
    }//GEN-LAST:event_itemGraficosActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(
                () -> {

                    Administrador administrador
                    = new Administrador();

                    administrador.setNome(
                            "Administrador"
                    );

                    TelaMenuAdministrador tela
                    = new TelaMenuAdministrador(
                            administrador
                    );

                    tela.setVisible(true);
                }
        );
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAdministradores;
    private javax.swing.JMenuItem itemAlimentos;
    private javax.swing.JMenuItem itemAprovacao;
    private javax.swing.JMenuItem itemCategorias;
    private javax.swing.JMenuItem itemDoadores;
    private javax.swing.JMenuItem itemEntregas;
    private javax.swing.JMenuItem itemGraficos;
    private javax.swing.JMenuItem itemInstituicoes;
    private javax.swing.JMenuItem itemRelatorios;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemSolicitacoes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblIconeUsuario;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuSolicitacoes;
    // End of variables declaration//GEN-END:variables
}
