package view;

import dao.EntregaDAO;
import dao.ItemSolicitacaoDAO;
import dao.AlimentoDAO;

import model.Entrega;
import model.Alimento;
import model.ItemSolicitacao;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaEntrega extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEntrega.class.getName());
    private EntregaDAO entregaDAO
            = new EntregaDAO();

    private ItemSolicitacaoDAO itemSolicitacaoDAO
            = new ItemSolicitacaoDAO();

    private AlimentoDAO alimentoDAO
            = new AlimentoDAO();

    private int id_entrega_selecionada = 0;

    private final DateTimeFormatter formato_data
            = DateTimeFormatter.ofPattern(
                    "dd/MM/yyyy"
            );

    public TelaEntrega() {
        initComponents();
        setLocationRelativeTo(null);

        carregarSolicitacoes();
        carregarTabela();
    }

    private void carregarItensDaSolicitacao(
            int fk_solicitacao) {

        DefaultTableModel modelo
                = (DefaultTableModel) tableItens.getModel();

        modelo.setRowCount(0);

        if (fk_solicitacao == 0) {
            return;
        }

        List<ItemSolicitacao> itens
                = itemSolicitacaoDAO
                        .listarPorSolicitacao(
                                fk_solicitacao
                        );

        List<Alimento> alimentos
                = alimentoDAO.listar();

        for (ItemSolicitacao item
                : itens) {

            String nome_alimento = "";
            String unidade_medida = "";

            for (Alimento alimento
                    : alimentos) {

                if (alimento.getId_alimento()
                        == item.getFk_alimento()) {

                    nome_alimento
                            = alimento.getNome();

                    unidade_medida
                            = alimento.getUnidade_medida();

                    break;
                }
            }

            modelo.addRow(new Object[]{
                nome_alimento,
                item.getQuantidade_solicitada(),
                unidade_medida
            });
        }
    }

    private void carregarSolicitacoes() {

        cbSolicitacao.removeAllItems();

        List<Integer> lista
                = entregaDAO.listarSolicitacoesDisponiveis();

        for (Integer id
                : lista) {

            cbSolicitacao.addItem(
                    "Solicitação #" + id
            );
        }
    }

    private int obterIdSolicitacaoSelecionada() {

        if (cbSolicitacao.getSelectedItem() == null) {
            return 0;
        }

        String texto
                = cbSolicitacao
                        .getSelectedItem()
                        .toString();

        return Integer.parseInt(
                texto.replace(
                        "Solicitação #",
                        ""
                )
        );
    }

    private void carregarTabela() {

        DefaultTableModel modelo
                = (DefaultTableModel) tableEntregas.getModel();

        modelo.setRowCount(0);

        List<Entrega> lista
                = entregaDAO.listar();

        for (Entrega entrega
                : lista) {

            modelo.addRow(new Object[]{
                entrega.getId_entrega(),
                "Solicitação #"
                + entrega.getFk_solicitacao(),
                entrega.getData_entrega(),
                entrega.getResponsavel_entrega(),
                entrega.getStatus()
            });
        }
    }

    private void limparCampos() {

        txtDataEntrega.setText("");
        txtResponsavelEntrega.setText("");
        txtObservacao.setText("");

        id_entrega_selecionada = 0;

        tableEntregas.clearSelection();

        DefaultTableModel modelo
                = (DefaultTableModel) tableItens.getModel();

        modelo.setRowCount(0);

        if (cbSolicitacao.getItemCount() > 0) {
            cbSolicitacao.setSelectedIndex(0);
        }

        cbSolicitacao.setEnabled(true);

        if (cbStatus.getItemCount() > 0) {
            cbStatus.setSelectedItem(
                    "REGISTRADA"
            );
        }

        txtDataEntrega.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSolicitacao = new javax.swing.JLabel();
        lblDataEntrega = new javax.swing.JLabel();
        lblResponsavelEntrega = new javax.swing.JLabel();
        lblObservacao = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        cbSolicitacao = new javax.swing.JComboBox<>();
        txtDataEntrega = new javax.swing.JTextField();
        txtResponsavelEntrega = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        cbStatus = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitulo2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEntregas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableItens = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 245));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo.setText("GERENCIAR ENTREGAS");

        lblSolicitacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSolicitacao.setForeground(new java.awt.Color(38, 50, 56));
        lblSolicitacao.setText("Solicitação:");

        lblDataEntrega.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDataEntrega.setForeground(new java.awt.Color(38, 50, 56));
        lblDataEntrega.setText("Data da Entrega:");

        lblResponsavelEntrega.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblResponsavelEntrega.setForeground(new java.awt.Color(38, 50, 56));
        lblResponsavelEntrega.setText("Responsável:");

        lblObservacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblObservacao.setForeground(new java.awt.Color(38, 50, 56));
        lblObservacao.setText("Observação:");

        lblStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(38, 50, 56));
        lblStatus.setText("Status:");

        cbSolicitacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbSolicitacao.setForeground(new java.awt.Color(38, 50, 56));
        cbSolicitacao.setToolTipText("Solicitações");
        cbSolicitacao.addActionListener(this::cbSolicitacaoActionPerformed);

        txtDataEntrega.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDataEntrega.setToolTipText("Data da Entrega");
        txtDataEntrega.setCaretColor(new java.awt.Color(38, 50, 56));

        txtResponsavelEntrega.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtResponsavelEntrega.setToolTipText("Responsável");
        txtResponsavelEntrega.setCaretColor(new java.awt.Color(38, 50, 56));

        txtObservacao.setColumns(20);
        txtObservacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtObservacao.setForeground(new java.awt.Color(38, 50, 56));
        txtObservacao.setLineWrap(true);
        txtObservacao.setRows(5);
        txtObservacao.setToolTipText("Observação");
        txtObservacao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtObservacao);

        cbStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbStatus.setForeground(new java.awt.Color(38, 50, 56));
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGISTRADA", "ENTREGUE", "CANCELADA" }));
        cbStatus.setToolTipText("Status");

        btnCadastrar.setBackground(new java.awt.Color(76, 175, 80));
        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Cadastrar");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.setOpaque(true);
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        btnAlterar.setBackground(new java.awt.Color(33, 150, 243));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setFocusPainted(false);
        btnAlterar.setOpaque(true);
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(229, 57, 53));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setFocusPainted(false);
        btnExcluir.setOpaque(true);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(96, 125, 139));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar");
        btnLimpar.setBorderPainted(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setFocusPainted(false);
        btnLimpar.setOpaque(true);
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        lblTitulo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo2.setText("ENTREGAS");

        tableEntregas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tableEntregas.setForeground(new java.awt.Color(38, 50, 56));
        tableEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Solicitação", "Data", "Responsável", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEntregas.setGridColor(new java.awt.Color(224, 224, 224));
        tableEntregas.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tableEntregas.setRowHeight(28);
        tableEntregas.setSelectionBackground(new java.awt.Color(232, 245, 233));
        tableEntregas.setSelectionForeground(new java.awt.Color(38, 50, 56));
        tableEntregas.setShowGrid(true);
        tableEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEntregasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableEntregas);
        if (tableEntregas.getColumnModel().getColumnCount() > 0) {
            tableEntregas.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableEntregas.getColumnModel().getColumn(1).setPreferredWidth(35);
            tableEntregas.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        tableItens.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tableItens.setForeground(new java.awt.Color(38, 50, 56));
        tableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Alimento", "Quantidade", "Unidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItens.setGridColor(new java.awt.Color(224, 224, 224));
        tableItens.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tableItens.setRowHeight(28);
        tableItens.setSelectionBackground(new java.awt.Color(232, 245, 233));
        tableItens.setSelectionForeground(new java.awt.Color(38, 50, 56));
        tableItens.setShowGrid(true);
        tableItens.setShowHorizontalLines(true);
        tableItens.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tableItens);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 125, 139));
        jLabel1.setText("Itens da Solicitação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSolicitacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblResponsavelEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtResponsavelEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btnCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSolicitacao)
                    .addComponent(cbSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResponsavelEntrega)
                    .addComponent(txtResponsavelEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblObservacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (cbSolicitacao.getSelectedItem()
                == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma solicitação."
            );

            return;
        }

        String data_texto
                = txtDataEntrega.getText().trim();

        String responsavel
                = txtResponsavelEntrega
                        .getText()
                        .trim();

        String observacao
                = txtObservacao
                        .getText()
                        .trim();

        if (data_texto.isEmpty()
                || responsavel.isEmpty()
                || observacao.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return;
        }

        try {

            LocalDate data_entrega
                    = LocalDate.parse(
                            data_texto,
                            formato_data
                    );

            int fk_solicitacao
                    = obterIdSolicitacaoSelecionada();

            if (fk_solicitacao == 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Solicitação inválida."
                );

                return;
            }

            Entrega entrega
                    = new Entrega();

            entrega.setData_entrega(
                    data_entrega
            );

            entrega.setResponsavel_entrega(
                    responsavel
            );

            entrega.setObservacao(
                    observacao
            );

            entrega.setStatus(
                    cbStatus
                            .getSelectedItem()
                            .toString()
            );

            entrega.setFk_solicitacao(
                    fk_solicitacao
            );

            entregaDAO.cadastrar(entrega);

            JOptionPane.showMessageDialog(
                    this,
                    "Entrega cadastrada com sucesso!"
            );

            limparCampos();
            carregarSolicitacoes();
            carregarTabela();

        } catch (DateTimeParseException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Digite a data no formato dd/MM/yyyy."
            );
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tableEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEntregasMouseClicked
        int linha
                = tableEntregas.getSelectedRow();

        if (linha < 0) {
            return;
        }

        id_entrega_selecionada
                = Integer.parseInt(
                        tableEntregas
                                .getValueAt(linha, 0)
                                .toString()
                );

        Entrega entrega
                = entregaDAO.buscarPorId(
                        id_entrega_selecionada
                );

        if (entrega == null) {
            return;
        }

        txtDataEntrega.setText(
                entrega.getData_entrega()
                        .format(formato_data)
        );

        txtResponsavelEntrega.setText(
                entrega.getResponsavel_entrega()
        );

        txtObservacao.setText(
                entrega.getObservacao()
        );

        cbStatus.setSelectedItem(
                entrega.getStatus()
        );

        String solicitacao
                = "Solicitação #"
                + entrega.getFk_solicitacao();

        cbSolicitacao.setSelectedItem(
                solicitacao
        );

        cbSolicitacao.setEnabled(false);

        carregarItensDaSolicitacao(
                entrega.getFk_solicitacao()
        );
    }//GEN-LAST:event_tableEntregasMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (id_entrega_selecionada == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma entrega."
            );

            return;
        }

        try {

            LocalDate data_entrega
                    = LocalDate.parse(
                            txtDataEntrega
                                    .getText()
                                    .trim(),
                            formato_data
                    );

            String responsavel
                    = txtResponsavelEntrega
                            .getText()
                            .trim();

            String observacao
                    = txtObservacao
                            .getText()
                            .trim();

            if (responsavel.isEmpty()
                    || observacao.isEmpty()) {

                JOptionPane.showMessageDialog(
                        this,
                        "Preencha todos os campos."
                );

                return;
            }

            Entrega entregaExistente
                    = entregaDAO.buscarPorId(
                            id_entrega_selecionada
                    );

            if (entregaExistente == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Entrega não encontrada."
                );

                return;
            }

            Entrega entrega
                    = new Entrega();

            entrega.setId_entrega(
                    id_entrega_selecionada
            );

            entrega.setData_entrega(
                    data_entrega
            );

            entrega.setResponsavel_entrega(
                    responsavel
            );

            entrega.setObservacao(
                    observacao
            );

            entrega.setStatus(
                    cbStatus
                            .getSelectedItem()
                            .toString()
            );

            entrega.setFk_solicitacao(
                    entregaExistente.getFk_solicitacao()
            );

            entregaDAO.atualizar(
                    entrega
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Entrega alterada com sucesso!"
            );

            limparCampos();
            carregarSolicitacoes();
            carregarTabela();

        } catch (DateTimeParseException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Data inválida. Use dd/MM/yyyy."
            );
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (id_entrega_selecionada == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma entrega."
            );

            return;
        }

        int resposta
                = JOptionPane.showConfirmDialog(
                        this,
                        "Deseja realmente excluir "
                        + "esta entrega?",
                        "Confirmação",
                        JOptionPane.YES_NO_OPTION
                );

        if (resposta
                == JOptionPane.YES_OPTION) {

            entregaDAO.excluir(
                    id_entrega_selecionada
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Entrega excluída com sucesso!"
            );

            limparCampos();
            carregarSolicitacoes();
            carregarTabela();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void cbSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSolicitacaoActionPerformed
        int fk_solicitacao
                = obterIdSolicitacaoSelecionada();

        carregarItensDaSolicitacao(
                fk_solicitacao
        );
    }//GEN-LAST:event_cbSolicitacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEntrega().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbSolicitacao;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDataEntrega;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblResponsavelEntrega;
    private javax.swing.JLabel lblSolicitacao;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tableEntregas;
    private javax.swing.JTable tableItens;
    private javax.swing.JTextField txtDataEntrega;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtResponsavelEntrega;
    // End of variables declaration//GEN-END:variables
}
