package view;

import dao.DoadorDAO;
import java.io.IOException;
import model.Doador;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import util.CepResposta;
import util.ViaCepUtil;
import util.MascaraUtil;

public class TelaDoador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDoador.class.getName());

    private DoadorDAO doadorDAO = new DoadorDAO();
    private int idDoadorSelecionado = 0;

    public TelaDoador() {
        initComponents();

        MascaraUtil.aplicarMascaraCpfCnpj(
                txtCpfCnpj
        );

        MascaraUtil.aplicarMascaraTelefone(
                txtTelefone
        );

        MascaraUtil.aplicarMascaraCep(
                txtCep
        );

        setLocationRelativeTo(null);

        carregarTabela();
    }

    private void carregarTabela() {

        DefaultTableModel modelo = (DefaultTableModel) tableDoadores.getModel();

        modelo.setRowCount(0);

        List<Doador> lista = doadorDAO.listar();

        for (Doador doador : lista) {

            modelo.addRow(new Object[]{
                doador.getId_doador(),
                doador.getNome(),
                MascaraUtil.formatarCpfCnpj(
                doador.getCpf_cnpj()
                ),
                MascaraUtil.formatarTelefone(
                doador.getTelefone()
                ),
                MascaraUtil.formatarCep(
                doador.getCep()
                ),
                doador.getRua(),
                doador.getNumero(),
                doador.getBairro()
            });

        }
    }

    private void limparCampos() {

        txtNome.setText("");
        txtCpfCnpj.setText("");
        txtTelefone.setText("");
        txtCep.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtBairro.setText("");

        idDoadorSelecionado = 0;

        tableDoadores.clearSelection();

        txtNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCpfCnpj = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpfCnpj = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnBuscarCep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDoadores = new javax.swing.JTable();
        lblTitulo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 245));

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(38, 50, 56));
        lblNome.setText("Nome:");

        lblCpfCnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCpfCnpj.setForeground(new java.awt.Color(38, 50, 56));
        lblCpfCnpj.setText("CPF/CNPJ:");

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo.setText("GERENCIAR DOADORES");

        lblTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(38, 50, 56));
        lblTelefone.setText("Telefone:");

        lblCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCep.setForeground(new java.awt.Color(38, 50, 56));
        lblCep.setText("CEP:");

        lblRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRua.setForeground(new java.awt.Color(38, 50, 56));
        lblRua.setText("Rua:");

        lblNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(38, 50, 56));
        lblNumero.setText("Número:");

        lblBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(38, 50, 56));
        lblBairro.setText("Bairro:");

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(38, 50, 56));
        txtNome.setToolTipText("Nome");
        txtNome.addActionListener(this::txtNomeActionPerformed);

        txtCpfCnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCpfCnpj.setForeground(new java.awt.Color(38, 50, 56));
        txtCpfCnpj.setToolTipText("CPF ou CNPJ");

        txtTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(38, 50, 56));
        txtTelefone.setToolTipText("Telefone");

        txtCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCep.setForeground(new java.awt.Color(38, 50, 56));
        txtCep.setToolTipText("CEP");

        txtRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRua.setForeground(new java.awt.Color(38, 50, 56));
        txtRua.setToolTipText("Rua");
        txtRua.addActionListener(this::txtRuaActionPerformed);

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(38, 50, 56));
        txtNumero.setToolTipText("Número");

        txtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairro.setForeground(new java.awt.Color(38, 50, 56));
        txtBairro.setToolTipText("Bairro");

        btnCadastrar.setBackground(new java.awt.Color(76, 175, 80));
        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Cadastrar");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.setOpaque(true);
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        btnAlterar.setBackground(new java.awt.Color(33, 150, 243));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setFocusPainted(false);
        btnAlterar.setOpaque(true);
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(229, 57, 53));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setFocusPainted(false);
        btnExcluir.setOpaque(true);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(96, 125, 139));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar");
        btnLimpar.setBorderPainted(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setFocusPainted(false);
        btnLimpar.setOpaque(true);
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnBuscarCep.setBackground(new java.awt.Color(33, 150, 243));
        btnBuscarCep.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnBuscarCep.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCep.setText("Buscar CEP");
        btnBuscarCep.setToolTipText("Buscar CEP");
        btnBuscarCep.setBorderPainted(false);
        btnBuscarCep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCep.setFocusPainted(false);
        btnBuscarCep.setOpaque(true);
        btnBuscarCep.addActionListener(this::btnBuscarCepActionPerformed);

        tableDoadores.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tableDoadores.setForeground(new java.awt.Color(38, 50, 56));
        tableDoadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF/CNPJ", "Telefone", "CEP", "Rua", "Número", "Bairro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDoadores.setGridColor(new java.awt.Color(224, 224, 224));
        tableDoadores.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tableDoadores.setRowHeight(28);
        tableDoadores.setSelectionBackground(new java.awt.Color(232, 245, 233));
        tableDoadores.setSelectionForeground(new java.awt.Color(38, 50, 56));
        tableDoadores.setShowGrid(true);
        tableDoadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDoadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDoadores);
        if (tableDoadores.getColumnModel().getColumnCount() > 0) {
            tableDoadores.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableDoadores.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableDoadores.getColumnModel().getColumn(6).setPreferredWidth(60);
        }

        lblTitulo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo2.setText("DOADORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTelefone)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtTelefone))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCpfCnpj)
                                        .addGap(16, 16, 16)
                                        .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addGap(46, 46, 46)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCep)
                                .addGap(128, 128, 128))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBairro)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblNumero)
                                            .addGap(33, 33, 33)
                                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblRua)
                                            .addGap(56, 56, 56)
                                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(12, 12, 12)
                        .addComponent(btnAlterar)
                        .addGap(14, 14, 14)
                        .addComponent(btnExcluir)
                        .addGap(14, 14, 14)
                        .addComponent(btnLimpar)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNome))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCpfCnpj))
                    .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTelefone))
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCep))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCep)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblRua))
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNumero))
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblBairro))
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText().trim();
        String cpf_cnpj
                = MascaraUtil.somenteNumeros(
                        txtCpfCnpj.getText()
                );

        String telefone
                = MascaraUtil.somenteNumeros(
                        txtTelefone.getText()
                );

        String cep
                = MascaraUtil.somenteNumeros(
                        txtCep.getText()
                );
        String rua = txtRua.getText().trim();
        String numero = txtNumero.getText().trim();
        String bairro = txtBairro.getText().trim();

        if (nome.isEmpty()
                || cpf_cnpj.isEmpty()
                || telefone.isEmpty()
                || cep.isEmpty()
                || rua.isEmpty()
                || numero.isEmpty()
                || bairro.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Preencha todos os campos.");

            return;
        }

        if (cpf_cnpj.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Informe o CPF/CNPJ."
            );

            return;
        }

        if (cpf_cnpj.length() > 18) {

            JOptionPane.showMessageDialog(
                    this,
                    "O CPF/CNPJ deve possuir no máximo 18 caracteres."
            );

            return;
        }

        if (telefone.length() < 10) {

            JOptionPane.showMessageDialog(
                    this,
                    "Informe um telefone válido."
            );

            return;
        }

        Doador doador = new Doador();

        doador.setNome(nome);
        doador.setCpf_cnpj(cpf_cnpj);
        doador.setTelefone(telefone);
        doador.setCep(cep);
        doador.setRua(rua);
        doador.setNumero(numero);
        doador.setBairro(bairro);

        doadorDAO.cadastrar(doador);

        JOptionPane.showMessageDialog(this,
                "Doador cadastrado com sucesso!");

        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (idDoadorSelecionado == 0) {

            JOptionPane.showMessageDialog(this,
                    "Selecione um doador na tabela.");

            return;
        }

        String nome = txtNome.getText().trim();
        String cpf_cnpj
                = MascaraUtil.somenteNumeros(
                        txtCpfCnpj.getText()
                );

        String telefone
                = MascaraUtil.somenteNumeros(
                        txtTelefone.getText()
                );

        String cep
                = MascaraUtil.somenteNumeros(
                        txtCep.getText()
                );
        String rua = txtRua.getText().trim();
        String numero = txtNumero.getText().trim();
        String bairro = txtBairro.getText().trim();

        if (nome.isEmpty()
                || cpf_cnpj.isEmpty()
                || telefone.isEmpty()
                || cep.isEmpty()
                || rua.isEmpty()
                || numero.isEmpty()
                || bairro.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Preencha todos os campos.");

            return;
        }

        Doador doador = new Doador();

        doador.setId_doador(idDoadorSelecionado);
        doador.setNome(nome);
        doador.setCpf_cnpj(cpf_cnpj);
        doador.setTelefone(telefone);
        doador.setCep(cep);
        doador.setRua(rua);
        doador.setNumero(numero);
        doador.setBairro(bairro);

        doadorDAO.atualizar(doador);

        JOptionPane.showMessageDialog(this,
                "Doador alterado com sucesso!");

        limparCampos();
        carregarTabela();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (idDoadorSelecionado == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um doador na tabela."
            );

            return;
        }

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir este doador?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {

            boolean excluiu
                    = doadorDAO.excluir(
                            idDoadorSelecionado
                    );

            if (excluiu) {

                JOptionPane.showMessageDialog(
                        this,
                        "Doador excluído com sucesso!",
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE
                );

                limparCampos();
                carregarTabela();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Não é possível excluir este doador.\n\n"
                        + "Ele possui alimentos cadastrados "
                        + "vinculados a ele.\n"
                        + "Altere ou exclua os alimentos relacionados "
                        + "antes de excluir o doador.",
                        "Doador vinculado",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCepActionPerformed
        String cep
                = MascaraUtil.somenteNumeros(
                        txtCep.getText()
                );

        if (cep.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Digite um CEP."
            );

            return;
        }

        try {

            CepResposta resposta
                    = ViaCepUtil.buscar(cep);

            if (resposta.isErro()) {

                JOptionPane.showMessageDialog(
                        this,
                        "CEP não encontrado."
                );

                return;
            }

            if (!"Santa Fé do Sul"
                    .equalsIgnoreCase(
                            resposta.getLocalidade()
                    )
                    || !"SP".equalsIgnoreCase(
                            resposta.getUf()
                    )) {

                JOptionPane.showMessageDialog(
                        this,
                        "O CEP deve pertencer a "
                        + "Santa Fé do Sul - SP."
                );

                return;
            }

            txtRua.setText(
                    resposta.getLogradouro()
            );

            txtBairro.setText(
                    resposta.getBairro()
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Endereço preenchido com sucesso!"
            );

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "CEP inválido. Digite 8 números."
            );

        } catch (IOException
                | InterruptedException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Não foi possível consultar o CEP."
            );
        }
    }//GEN-LAST:event_btnBuscarCepActionPerformed

    private void tableDoadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDoadoresMouseClicked
        int linha = tableDoadores.getSelectedRow();

        if (linha >= 0) {

            idDoadorSelecionado = Integer.parseInt(
                    tableDoadores.getValueAt(linha, 0).toString()
            );

            txtNome.setText(
                    tableDoadores
                            .getValueAt(linha, 1)
                            .toString()
            );

            txtCpfCnpj.setText(
                    MascaraUtil.formatarCpfCnpj(
                            tableDoadores
                                    .getValueAt(linha, 2)
                                    .toString()
                    )
            );

            txtTelefone.setText(
                    MascaraUtil.formatarTelefone(
                            tableDoadores
                                    .getValueAt(linha, 3)
                                    .toString()
                    )
            );

            txtCep.setText(
                    MascaraUtil.formatarCep(
                            tableDoadores
                                    .getValueAt(linha, 4)
                                    .toString()
                    )
            );

            txtRua.setText(
                    tableDoadores.getValueAt(linha, 5).toString()
            );

            txtNumero.setText(
                    tableDoadores.getValueAt(linha, 6).toString()
            );

            txtBairro.setText(
                    tableDoadores.getValueAt(linha, 7).toString()
            );
        }
    }//GEN-LAST:event_tableDoadoresMouseClicked

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDoador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarCep;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tableDoadores;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
