package view;

import dao.InstituicaoDAO;
import java.io.IOException;
import model.Instituicao;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import util.CepResposta;
import util.ViaCepUtil;
import util.MascaraUtil;

public class TelaInstituicao extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInstituicao.class.getName());
    private InstituicaoDAO instituicaoDAO = new InstituicaoDAO();

    private int idInstituicaoSelecionada = 0;

    public TelaInstituicao() {
        initComponents();

        MascaraUtil.aplicarMascaraCpfCnpj(
                txtCnpj
        );

        MascaraUtil.aplicarMascaraCep(
                txtCep
        );

        setLocationRelativeTo(null);

        carregarTabela();
    }

    private void carregarTabela() {

        DefaultTableModel modelo
                = (DefaultTableModel) tableInstituicoes.getModel();

        modelo.setRowCount(0);

        List<Instituicao> lista = instituicaoDAO.listar();

        for (Instituicao instituicao : lista) {

            modelo.addRow(new Object[]{
                instituicao.getId_instituicao(),
                instituicao.getNome(),
                MascaraUtil.formatarCpfCnpj(
                instituicao.getCnpj()
                ),
                instituicao.getResponsavel(),
                MascaraUtil.formatarCep(
                instituicao.getCep()
                ),
                instituicao.getRua(),
                instituicao.getNumero(),
                instituicao.getBairro()
            });
        }
    }

    private void limparCampos() {

        txtNome.setText("");
        txtCnpj.setText("");
        txtResponsavel.setText("");
        txtCep.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtBairro.setText("");

        idInstituicaoSelecionada = 0;

        tableInstituicoes.clearSelection();

        txtNome.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        lblResponsavel = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtResponsavel = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        btnBuscarCep = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInstituicoes = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 245));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo.setText("GERENCIAR INSTITUIÇÕES");

        lblCnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCnpj.setForeground(new java.awt.Color(38, 50, 56));
        lblCnpj.setText("CNPJ:");

        lblResponsavel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblResponsavel.setForeground(new java.awt.Color(38, 50, 56));
        lblResponsavel.setText("Responsável:");

        lblCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCep.setForeground(new java.awt.Color(38, 50, 56));
        lblCep.setText("CEP:");

        lblRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRua.setForeground(new java.awt.Color(38, 50, 56));
        lblRua.setText("Rua:");

        lblNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(38, 50, 56));
        lblNumero.setText("Número:");

        lblBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(38, 50, 56));
        lblBairro.setText("Bairro:");

        txtCnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCnpj.setForeground(new java.awt.Color(38, 50, 56));
        txtCnpj.setToolTipText("CNPJ");
        txtCnpj.addActionListener(this::txtCnpjActionPerformed);

        txtResponsavel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtResponsavel.setForeground(new java.awt.Color(38, 50, 56));
        txtResponsavel.setToolTipText("Responsável");

        txtCep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCep.setForeground(new java.awt.Color(38, 50, 56));
        txtCep.setToolTipText("CEP");

        txtRua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRua.setForeground(new java.awt.Color(38, 50, 56));
        txtRua.setToolTipText("Rua");

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(38, 50, 56));
        txtNumero.setToolTipText("Número");

        txtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairro.setForeground(new java.awt.Color(38, 50, 56));
        txtBairro.setToolTipText("Bairro");

        btnBuscarCep.setBackground(new java.awt.Color(33, 150, 243));
        btnBuscarCep.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnBuscarCep.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCep.setText("Buscar CEP");
        btnBuscarCep.setToolTipText("Buscar CEP");
        btnBuscarCep.setBorderPainted(false);
        btnBuscarCep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCep.setFocusPainted(false);
        btnBuscarCep.setOpaque(true);
        btnBuscarCep.addActionListener(this::btnBuscarCepActionPerformed);

        btnCadastrar.setBackground(new java.awt.Color(76, 175, 80));
        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Cadastrar");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.setOpaque(true);
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        btnAlterar.setBackground(new java.awt.Color(33, 150, 243));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setFocusPainted(false);
        btnAlterar.setOpaque(true);
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(229, 57, 53));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setFocusPainted(false);
        btnExcluir.setOpaque(true);
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnLimpar.setBackground(new java.awt.Color(96, 125, 139));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpar");
        btnLimpar.setBorderPainted(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setFocusPainted(false);
        btnLimpar.setOpaque(true);
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        lblTitulo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(46, 125, 50));
        lblTitulo2.setText("INSTITUIÇÕES");

        tableInstituicoes.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tableInstituicoes.setForeground(new java.awt.Color(38, 50, 56));
        tableInstituicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Instituição", "CNPJ", "Responsável", "CEP", "Rua", "Número", "Bairro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInstituicoes.setGridColor(new java.awt.Color(224, 224, 224));
        tableInstituicoes.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tableInstituicoes.setRowHeight(28);
        tableInstituicoes.setSelectionBackground(new java.awt.Color(232, 245, 233));
        tableInstituicoes.setSelectionForeground(new java.awt.Color(38, 50, 56));
        tableInstituicoes.setShowGrid(true);
        tableInstituicoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInstituicoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableInstituicoes);
        if (tableInstituicoes.getColumnModel().getColumnCount() > 0) {
            tableInstituicoes.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableInstituicoes.getColumnModel().getColumn(4).setPreferredWidth(60);
            tableInstituicoes.getColumnModel().getColumn(6).setPreferredWidth(60);
        }

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(38, 50, 56));
        lblNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(38, 50, 56));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(txtResponsavel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblRua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(txtRua))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(txtNumero))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(txtBairro))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNome))
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                        .addComponent(txtCnpj))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCep))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(20, 20, 20)
                        .addComponent(btnAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCnpj)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResponsavel)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCep)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCep)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulo2)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome
                = txtNome.getText().trim();

        String cnpj
                = MascaraUtil.somenteNumeros(
                        txtCnpj.getText()
                );

        String responsavel
                = txtResponsavel.getText().trim();

        String cep
                = MascaraUtil.somenteNumeros(
                        txtCep.getText()
                );

        String rua
                = txtRua.getText().trim();

        String numero
                = txtNumero.getText().trim();

        String bairro
                = txtBairro.getText().trim();

        if (nome.isEmpty()
                || cnpj.isEmpty()
                || responsavel.isEmpty()
                || cep.isEmpty()
                || rua.isEmpty()
                || numero.isEmpty()
                || bairro.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return;
        }

        if (cnpj.length() != 14) {

            JOptionPane.showMessageDialog(
                    this,
                    "O CNPJ deve possuir 14 números."
            );

            return;
        }

        if (cep.length() != 8) {

            JOptionPane.showMessageDialog(
                    this,
                    "O CEP deve possuir 8 números."
            );

            return;
        }

        Instituicao instituicao
                = new Instituicao();

        instituicao.setNome(nome);

        instituicao.setCnpj(cnpj);

        instituicao.setResponsavel(
                responsavel
        );

        instituicao.setCep(cep);

        instituicao.setRua(rua);

        instituicao.setNumero(numero);

        instituicao.setBairro(bairro);

        instituicaoDAO.cadastrar(
                instituicao
        );

        JOptionPane.showMessageDialog(
                this,
                "Instituição cadastrada com sucesso!"
        );

        limparCampos();

        carregarTabela();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void tableInstituicoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInstituicoesMouseClicked
        int linha
                = tableInstituicoes.getSelectedRow();

        if (linha >= 0) {

            idInstituicaoSelecionada
                    = Integer.parseInt(
                            tableInstituicoes
                                    .getValueAt(linha, 0)
                                    .toString()
                    );

            txtNome.setText(
                    tableInstituicoes
                            .getValueAt(linha, 1)
                            .toString()
            );

            txtCnpj.setText(
                    MascaraUtil.formatarCpfCnpj(
                            tableInstituicoes
                                    .getValueAt(linha, 2)
                                    .toString()
                    )
            );

            txtResponsavel.setText(
                    tableInstituicoes
                            .getValueAt(linha, 3)
                            .toString()
            );

            txtCep.setText(
                    MascaraUtil.formatarCep(
                            tableInstituicoes
                                    .getValueAt(linha, 4)
                                    .toString()
                    )
            );

            txtRua.setText(
                    tableInstituicoes
                            .getValueAt(linha, 5)
                            .toString()
            );

            txtNumero.setText(
                    tableInstituicoes
                            .getValueAt(linha, 6)
                            .toString()
            );

            txtBairro.setText(
                    tableInstituicoes
                            .getValueAt(linha, 7)
                            .toString()
            );
        }
    }//GEN-LAST:event_tableInstituicoesMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (idInstituicaoSelecionada == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma instituição na tabela."
            );

            return;
        }

        String nome
                = txtNome.getText().trim();

        String cnpj
                = MascaraUtil.somenteNumeros(
                        txtCnpj.getText()
                );

        String responsavel
                = txtResponsavel.getText().trim();

        String cep
                = MascaraUtil.somenteNumeros(
                        txtCep.getText()
                );

        String rua
                = txtRua.getText().trim();

        String numero
                = txtNumero.getText().trim();

        String bairro
                = txtBairro.getText().trim();

        if (nome.isEmpty()
                || cnpj.isEmpty()
                || responsavel.isEmpty()
                || cep.isEmpty()
                || rua.isEmpty()
                || numero.isEmpty()
                || bairro.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return;
        }

        if (cnpj.length() != 14) {

            JOptionPane.showMessageDialog(
                    this,
                    "O CNPJ deve possuir 14 números."
            );

            return;
        }

        if (cep.length() != 8) {

            JOptionPane.showMessageDialog(
                    this,
                    "O CEP deve possuir 8 números."
            );

            return;
        }

        Instituicao instituicao
                = new Instituicao();

        instituicao.setId_instituicao(
                idInstituicaoSelecionada
        );

        instituicao.setNome(nome);

        instituicao.setCnpj(cnpj);

        instituicao.setResponsavel(
                responsavel
        );

        instituicao.setCep(cep);

        instituicao.setRua(rua);

        instituicao.setNumero(numero);

        instituicao.setBairro(bairro);

        instituicaoDAO.atualizar(
                instituicao
        );

        JOptionPane.showMessageDialog(
                this,
                "Instituição alterada com sucesso!"
        );

        limparCampos();

        carregarTabela();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (idInstituicaoSelecionada == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Selecione uma instituição na tabela."
            );

            return;
        }

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir esta instituição?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {

            boolean excluiu
                    = instituicaoDAO.excluir(
                            idInstituicaoSelecionada
                    );

            if (excluiu) {

                JOptionPane.showMessageDialog(
                        this,
                        "Instituição excluída com sucesso!",
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE
                );

                limparCampos();
                carregarTabela();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Não é possível excluir esta instituição.\n\n"
                        + "Ela possui solicitações cadastradas "
                        + "vinculadas a ela.\n"
                        + "Para preservar o histórico das solicitações, "
                        + "a instituição não pode ser excluída.",
                        "Instituição vinculada",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCepActionPerformed
        String cep
                = MascaraUtil.somenteNumeros(
                        txtCep.getText()
                );

        if (cep.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Digite um CEP."
            );

            return;
        }

        try {

            CepResposta resposta
                    = ViaCepUtil.buscar(cep);

            if (resposta.isErro()) {

                JOptionPane.showMessageDialog(
                        this,
                        "CEP não encontrado."
                );

                return;
            }

            if (!"Santa Fé do Sul"
                    .equalsIgnoreCase(
                            resposta.getLocalidade()
                    )
                    || !"SP".equalsIgnoreCase(
                            resposta.getUf()
                    )) {

                JOptionPane.showMessageDialog(
                        this,
                        "O CEP deve pertencer a "
                        + "Santa Fé do Sul - SP."
                );

                return;
            }

            txtRua.setText(
                    resposta.getLogradouro()
            );

            txtBairro.setText(
                    resposta.getBairro()
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Endereço preenchido com sucesso!"
            );

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "CEP inválido."
            );

        } catch (IOException
                | InterruptedException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Não foi possível consultar o CEP."
            );
        }
    }//GEN-LAST:event_btnBuscarCepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInstituicao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarCep;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tableInstituicoes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
